apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-back-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-back
  template:
    metadata:
      labels:
        app: front-back
    spec:
      containers:
        - name: front-container
          image: sergeilukin/front-image:latest
          ports:
            - containerPort: 5173:5173
        - name: back-container
          image: sergeilukin/back-image:latest
          ports:
            - containerPort: 3000:3000

